# Generated by Django 6.0.5 on 2026-06-02 10:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('certificate_type', models.CharField(choices=[('bonafide', 'Bonafide Certificate'), ('study', 'Study Certificate'), ('transfer', 'Transfer Certificate'), ('course_completion', 'Course Completion Certificate'), ('medium', 'Medium of Instruction Certificate'), ('provisional', 'Provisional Certificate'), ('migration', 'Migration Certificate'), ('income', 'Income Certificate'), ('internship', 'Internship Certificate'), ('character', 'Character Certificate')], max_length=30)),
                ('purpose', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_verification', 'Under Verification'), ('document_issue', 'Document Issue'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('generated', 'Certificate Generated'), ('delivered', 'Delivered')], default='submitted', max_length=20)),
                ('is_tatkal', models.BooleanField(default=False)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('staff_remarks', models.TextField(blank=True)),
                ('document1', models.FileField(blank=True, null=True, upload_to='application_docs/')),
                ('document2', models.FileField(blank=True, null=True, upload_to='application_docs/')),
                ('document3', models.FileField(blank=True, null=True, upload_to='application_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='certificates.application')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('verification_code', models.CharField(max_length=20, unique=True)),
                ('pdf_path', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('download_count', models.IntegerField(default=0)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='certificates.application')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
