# Generated by Django 6.0.5 on 2026-06-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='university',
            field=models.CharField(blank=True, choices=[('jntu_hyd', 'JNTU Hyderabad'), ('jntu_kak', 'JNTU Kakinada'), ('jntu_ana', 'JNTU Anantapur'), ('private', 'Private University')], default='', max_length=20),
        ),
    ]
