# Generated by Django 6.0.5 on 2026-06-02 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_institution_remove_studentprofile_university_and_more'),
        ('certificates', '0002_application_university'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='university',
        ),
        migrations.AddField(
            model_name='application',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.institution'),
        ),
    ]
