# Generated by Django 6.0.5 on 2026-06-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='university',
            field=models.CharField(choices=[('jntu_hyd', 'JNTU Hyderabad'), ('jntu_kak', 'JNTU Kakinada'), ('jntu_ana', 'JNTU Anantapur'), ('private', 'Private University')], default='jntu_hyd', max_length=20),
        ),
    ]
